name: BIO_ENV
channels:
  - defaults
  - conda-forge
dependencies:
  - appnope=0.1.2
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - branca=0.5.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=37.0.1
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - folium=0.13.0
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - idna=3.3
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=8.4.0
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9e
  - jupyter_client=7.3.5
  - kiwisolver=1.4.2
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.8
  - libffi=3.3
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - numexpr=2.8.3
  - numpy=1.23.3
  - numpy-base=1.23.3
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.4
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - prompt-toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.6
  - python-dateutil=2.8.2
  - pytz=2022.1
  - pyzmq=23.2.0
  - readline=8.1.2
  - requests=2.28.1
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.3
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.2
  - tzdata=2022e
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.6
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - anyio=
    - argon2-cffi=
    - argon2-cffi-bindings=
    - attrs=
    - beautifulsoup4=
    - bleach=
    - click=
    - click-plugins=
    - cligj=
    - defusedxml=
    - fastjsonschema=
    - fiona=
    - geopandas=
    - ipyleaflet=
    - ipython-genutils=
    - ipywidgets=
    - joblib=
    - jsonschema=
    - jupyter-core=
    - jupyter-server=
    - jupyterlab-pygments=
    - jupyterlab-widgets=
    - mistune=
    - munch=
    - nbclassic=
    - nbclient=
    - nbconvert=
    - nbformat=
    - networkx=
    - notebook=
    - notebook-shim=
    - osmnx=
    - pandocfilters=
    - platformdirs=
    - polyline=
    - prometheus-client=
    - pyproj=
    - pyrsistent=
    - rtree=
    - scikit-learn=
    - scipy=
    - send2trash=
    - shapely=
    - sniffio=
    - soupsieve=
    - terminado=
    - threadpoolctl=
    - tinycss2=
    - tqdm=
    - traitlets=
    - traittypes=
    - webencodings=
    - websocket-client=
    - widgetsnbextension=
    - xyzservices=
